openapi: 3.0.3
info:
  title: JAWE
  description: JAWE Backend API services
  version: 0.1.0
components:
  schemas: {}
paths:
  /health:
    get:
      responses:
        "200":
          description: Default Response
  /api/v1/workflow-template/:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
        required: true
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required:
                  - id
    get:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    createdAt:
                      format: date-time
                      type: string
                    status:
                      anyOf:
                        - type: string
                          enum:
                            - DRAFT
                        - type: string
                          enum:
                            - PUBLISHED
                  required:
                    - id
                    - name
                    - createdAt
                    - status
  /api/v1/workflow-template/{id}:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  status:
                    anyOf:
                      - type: string
                        enum:
                          - DRAFT
                      - type: string
                        enum:
                          - PUBLISHED
                  entryPointId:
                    type: string
                  steps:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        type:
                          type: string
                        inputs: {}
                        visualizationMetadata:
                          type: object
                          properties:
                            position:
                              type: object
                              properties:
                                x:
                                  type: number
                                y:
                                  type: number
                              required:
                                - x
                                - y
                            data:
                              type: object
                              properties:
                                label:
                                  type: string
                              required:
                                - label
                          required:
                            - position
                            - data
                      required:
                        - id
                        - name
                        - type
                        - visualizationMetadata
                  connections:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        fromStepId:
                          type: string
                        toStepId:
                          type: string
                      required:
                        - id
                        - fromStepId
                        - toStepId
                  updatedAt:
                    format: date-time
                    type: string
                  triggers:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        settings: {}
                        visualizationMetadata:
                          type: object
                          properties:
                            position:
                              type: object
                              properties:
                                x:
                                  type: number
                                y:
                                  type: number
                              required:
                                - x
                                - y
                            data:
                              type: object
                              properties:
                                label:
                                  type: string
                              required:
                                - label
                          required:
                            - position
                            - data
                      required:
                        - id
                        - type
                        - settings
                        - visualizationMetadata
                required:
                  - id
                  - name
                  - status
                  - updatedAt
                  - triggers
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                steps:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      type:
                        type: string
                      inputs: {}
                      visualizationMetadata:
                        type: object
                        properties:
                          position:
                            type: object
                            properties:
                              x:
                                type: number
                              y:
                                type: number
                            required:
                              - x
                              - y
                          data:
                            type: object
                            properties:
                              label:
                                type: string
                            required:
                              - label
                        required:
                          - position
                          - data
                    required:
                      - id
                      - name
                      - type
                      - visualizationMetadata
                connections:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      fromStepId:
                        type: string
                      toStepId:
                        type: string
                    required:
                      - id
                      - fromStepId
                      - toStepId
                entryPointId:
                  type: string
                status:
                  anyOf:
                    - type: string
                      enum:
                        - DRAFT
                    - type: string
                      enum:
                        - PUBLISHED
                triggers:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      settings: {}
                      visualizationMetadata:
                        type: object
                        properties:
                          position:
                            type: object
                            properties:
                              x:
                                type: number
                              y:
                                type: number
                            required:
                              - x
                              - y
                          data:
                            type: object
                            properties:
                              label:
                                type: string
                            required:
                              - label
                        required:
                          - position
                          - data
                    required:
                      - id
                      - type
                      - settings
                      - visualizationMetadata
              required:
                - triggers
        required: true
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required:
                  - id
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
    delete:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                required:
                  - success
                  - message
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
  /api/v1/workflow-template/{id}/publish:
    patch:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                required:
                  - success
                  - message
        "400":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
  /api/v1/plugin/:
    get:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    id:
                      type: string
                    description:
                      type: string
                  required:
                    - name
                    - id
                    - description
  /api/v1/plugin/{id}:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  inputs:
                    type: object
                    additionalProperties: {}
                  outputs:
                    type: object
                    additionalProperties: {}
                required:
                  - id
                  - name
                  - description
                  - inputs
                  - outputs
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
  /api/v1/trigger/:
    get:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    id:
                      type: string
                    description:
                      type: string
                  required:
                    - name
                    - id
                    - description
  /api/v1/trigger/{id}:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                required:
                  - id
                  - name
                  - description
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
tags: []
