openapi: 3.0.3
info:
  title: JAWE
  description: JAWE Backend API services
  version: 0.1.0
components:
  schemas: {}
paths:
  /health:
    get:
      responses:
        "200":
          description: Default Response
tags: []
